base_app/urls.py
from django.urls import path
from . views import base_app_views, contact_views

app_name = 'base_app'

urlpatterns = [
    path('', base_app_views, name='base_app_views'),
    path('contact/', contact_views, name='contact')
]

kaban_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls', namespace='base_app')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('manager/', include('manager.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservations_list, update_reservations


urlpatterns = [
    path('reservations/', reservations_list, name='reservations_list'),
    path('reservations/update/<int:pk>', update_reservations, name='update_reserve')
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Весёлый Кабанчик!</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href={% static "img/logo.png" %} rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href={% static "lib/animate/animate.min.css" %}  rel="stylesheet">
    <link href={% static "lib/owlcarousel/assets/owl.carousel.min.css" %}  rel="stylesheet">
    <link href={% static "lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" %}  rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href={% static "css/bootstrap.min.css" %}  rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href={% static "css/style.css" %}  rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
         Spinner End -->


        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><img src={% static "img/logo.png"%} alt="">Весёлый Кабанчик</h1>

                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href='{% url 'base_app:base_app_views' %}' class="nav-item nav-link active">Главная</a>
                        <a href="#about" class="nav-item nav-link">о нас</a>
                        <a href="#service" class="nav-item nav-link">Сервесы</a>
                        <a href="#hero" class="nav-item nav-link">Меню</a>
                        {% if 'manager' in user.groups.all.0.name %}
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Менеджер</a>
                            <div class="dropdown-menu m-0">
                                <a href="{% url 'reservations_list' %}" class="dropdown-item">Резерваии</a>
                            </div>
                        </div>
                        {% endif %}
                        <a href="{% url 'base_app:contact' %}" class="nav-item nav-link">Контакты</a>
                    </div>
                    <a href="{% url 'login' %}" class="btn btn-primary py-2 px-4">Войти</a>
                </div>
            </nav>


        </div>
        <!-- Navbar & Hero End -->
<div class="container-xxl py-5 bg-dark hero-header mb-5" >
        {% for item in home %}
            <div class="container my-5 py-5">
                <div class="row align-items-center g-5">
                    <div class="col-lg-6 text-center text-lg-start">
                        <h1 class="display-3 text-white animated slideInLeft">{{ item.title_1 }}<br>{{ item.title_2 }}</h1>
                        <p class="text-white animated slideInLeft mb-4 pb-2">{{ item.desc }}</p>
                        <a href="#reservations" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">Забронировать стол</a>
                    </div>
                    <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                        <img class="img-fluid" src={% static "img/hero.png" %} alt="">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

        {% block content %}
        
        {% endblock %}
        

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Контакты</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">График работы</h4>
                        <h5 class="text-light fw-normal">Ежедневно</h5>
                        <p>с 11:00 до 21:00</p>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                            Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src={% static "lib/wow/wow.min.js" %}></script>
    <script src={% static "lib/easing/easing.min.js" %}></script>
    <script src={% static "lib/waypoints/waypoints.min.js" %}></script>
    <script src={% static "lib/counterup/counterup.min.js" %}></script>
    <script src={% static "lib/owlcarousel/owl.carousel.min.js" %}></script>
    <script src={% static "lib/tempusdominus/js/moment.min.js" %}></script>
    <script src={% static "lib/tempusdominus/js/moment-timezone.min.js" %}></script>
    <script src={% static "lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js" %}></script>

    <!-- Template Javascript -->
    <script src={% static "js/main.js" %}></script>
</body>

</html>